name: Consistent design with Flutter Theme
type: flutter
steps:
  - name: Introduction
    directory: 01_introduction
    has_solution: true
  - name: ThemeData
    directory: 02_themedata
    has_solution: true
  - name: Styling texts and icons
    directory: 03_texts_icons
    has_solution: true
  - name: Styling buttons
    directory: 04_buttons
    has_solution: true
