name: Consistent design with Flutter Theme
type: flutter
steps:
  - name: Introduction
    directory: 01_introduction
    has_solution: true
  - name: ThemeData
    directory: 02.1_themedata
    has_solution: true
  - name: Global ThemeData
    directory: 02.2_themedata
    has_solution: true
  - name: Styling texts and icons
    directory: 03_texts_icons
    has_solution: true
  - name: Styling buttons
    directory: 04_buttons
    has_solution: true
  - name: Styling inputs
    directory: 05_inputs
    has_solution: true
  - name: Styling screens
    directory: 06_screens
    has_solution: true
  - name: Conclusion
    directory: 07_conclusion
    has_solution: false
